@memberToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTIyNzMyNSwianRpIjoiMjY0NGY5ZGUtYTYyNC00Yzk1LThhMDQtOGU5MzA4OTBlNmM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3ODkyMjczMjUsImNzcmYiOiJmMmRkNzc0YS0zYmIxLTRlNDUtYjU0NC1lMTYzNWU0YzEzZTciLCJleHAiOjE3ODkyMjgyMjV9.qxVdleFZnsxS5z-tUgHSNBZ82P2ipBxxZFkM1G4ihhU
@librarianToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTIyNzM3MSwianRpIjoiNzk2MGEyYTQtZTZhNC00Mjk2LWJhYWMtZGNmYjcwMjdjYjJlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3ODkyMjczNzEsImNzcmYiOiI5YzViZmQxYS1kYjMzLTRmNmQtYjU2NC0wYzRkYzFlMjQyNjUiLCJleHAiOjE3ODkyMjgyNzF9.aBGNOzz7yilvu7oGf_UMZ5-MLjy9Lsoq3_Omas1aZ5k
@memberRefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTIyNzMyNSwianRpIjoiNjM3OTk3MTgtN2Q2Mi00Zjk4LWJjMDEtYjQ5ZGJiNjY4NDQ0IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxIiwibmJmIjoxNzg5MjI3MzI1LCJjc3JmIjoiZDgxZmFhNTUtMGRjNi00OGMwLWI4MTctMGY1NzMzOTQ1ZGUwIiwiZXhwIjoxNzkxODE5MzI1fQ.-TZqJhnyZWfJfWNOgi2S2m2cIWcLg1FJzm481MJZ2VQ
@baseUrl = http://127.0.0.1:5000

### Signup (member)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "member@example.com",
  "password": "Password123!"
}

### Signup (librarian)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "librarian@example.com",
  "password": "Password123!"
}

### Login (member)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "identifier": "member@example.com",
  "password": "Password123!"
}

### Login (librarian)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "identifier": "librarian@example.com",
  "password": "Password123!"
}

### Refresh (member)
POST {{baseUrl}}/auth/refresh
Authorization: Bearer {{memberRefreshToken}}

### Me (member)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{memberToken}}

### Guest area
GET {{baseUrl}}/auth/guest-area
Authorization: Bearer {{memberToken}}

### Member area
GET {{baseUrl}}/auth/member-area
Authorization: Bearer {{memberToken}}

### Admin area
GET {{baseUrl}}/auth/admin-area
Authorization: Bearer {{librarianToken}}