@memberToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI0NCwianRpIjoiY2I2YmY2OTctZDJhNC00NmMzLTg1YWItYWYzMzg0YzFhOTNlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3ODk5MjcyNDQsImNzcmYiOiJiMWIyYTgwNy1jMjZkLTRhOTQtYjQxNC0zMDE3YWVlYzhlZTIiLCJleHAiOjE3ODk5MzAyNDR9.xgaaHxnDlrLFGKc_ObrIDcbeYlMdw8KQmSj9BlUh5xQ
@librarianToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI5MiwianRpIjoiMGZlMjQ5YmQtMTdlYy00MDI1LTlkNTAtNmU2NjQ3NmEyZWZkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3ODk5MjcyOTIsImNzcmYiOiJjOTE5ZDdhZS05YzJjLTQzODctYWFmMy05M2YzZjkzOWQyMDYiLCJleHAiOjE3ODk5MzAyOTJ9.SQUvrXccC9RK8EEOBV2vNnydq79JxiVHTIKpsmxIYmo
@memberRefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI0NCwianRpIjoiZDNhMjcyZjYtZDg1Mi00OGQxLTg4NzUtNTdhYzAyNGEyZmQyIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxIiwibmJmIjoxNzg5OTI3MjQ0LCJjc3JmIjoiMGIzMjI0ODUtODAyMS00MTgwLWJiYzctYmFmZmMwZDM2ZWNkIiwiZXhwIjoxNzkyNTE5MjQ0fQ.5XCzZCDksJ3kcKSfN-1qch2y5cOL2qd1C5OYI1l_THk

@baseUrl = http://127.0.0.1:5000

### Signup (member)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "member@example.com",
  "password": "Password123!"
}

### Signup (librarian)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "librarian@example.com",
  "password": "Password123!"
}

### Login (member)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "identifier": "member@example.com",
  "password": "Password123!"
}

### Login (librarian)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "identifier": "librarian@example.com",
  "password": "Password123!"
}

### Refresh (member)
POST {{baseUrl}}/auth/refresh
Authorization: Bearer {{memberRefreshToken}}

### Me (member)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{memberToken}}

### Guest area
GET {{baseUrl}}/auth/guest-area
Authorization: Bearer {{memberToken}}

### Member area
GET {{baseUrl}}/auth/member-area
Authorization: Bearer {{memberToken}}

### Admin area
GET {{baseUrl}}/auth/admin-area
Authorization: Bearer {{librarianToken}}