@memberToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI0NCwianRpIjoiY2I2YmY2OTctZDJhNC00NmMzLTg1YWItYWYzMzg0YzFhOTNlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3ODk5MjcyNDQsImNzcmYiOiJiMWIyYTgwNy1jMjZkLTRhOTQtYjQxNC0zMDE3YWVlYzhlZTIiLCJleHAiOjE3ODk5MzAyNDR9.xgaaHxnDlrLFGKc_ObrIDcbeYlMdw8KQmSj9BlUh5xQ
@librarianToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI5MiwianRpIjoiMGZlMjQ5YmQtMTdlYy00MDI1LTlkNTAtNmU2NjQ3NmEyZWZkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3ODk5MjcyOTIsImNzcmYiOiJjOTE5ZDdhZS05YzJjLTQzODctYWFmMy05M2YzZjkzOWQyMDYiLCJleHAiOjE3ODk5MzAyOTJ9.SQUvrXccC9RK8EEOBV2vNnydq79JxiVHTIKpsmxIYmo
@memberRefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI0NCwianRpIjoiZDNhMjcyZjYtZDg1Mi00OGQxLTg4NzUtNTdhYzAyNGEyZmQyIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxIiwibmJmIjoxNzg5OTI3MjQ0LCJjc3JmIjoiMGIzMjI0ODUtODAyMS00MTgwLWJiYzctYmFmZmMwZDM2ZWNkIiwiZXhwIjoxNzkyNTE5MjQ0fQ.5XCzZCDksJ3kcKSfN-1qch2y5cOL2qd1C5OYI1l_THk
@baseUrl = http://127.0.0.1:5000
### Create loan request (member)
# Requires a book to exist. Use book_id=1 if you created "The Hobbit".
POST {{baseUrl}}/loan/demand
Authorization: Bearer {{memberToken}}
Content-Type: application/json

{
  "book_id": 1
}

### List pending loans (librarian)
GET {{baseUrl}}/loan/approved/1
Authorization: Bearer {{librarianToken}}

### Approve a pending loan (librarian)
POST {{baseUrl}}/loan/approved/1
Authorization: Bearer {{librarianToken}}
Content-Type: application/json

{
  "loan_id": 1,
  "due_date": "2026-10-01",
  "return_date": null
}

### Borrow (member)
POST {{baseUrl}}/loan/borrow
Authorization: Bearer {{memberToken}}
Content-Type: application/json

{
  "loan_id": 1
}

### Cancel (member)
DELETE {{baseUrl}}/loan/cancel/1
Authorization: Bearer {{memberToken}}