@memberToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI0NCwianRpIjoiY2I2YmY2OTctZDJhNC00NmMzLTg1YWItYWYzMzg0YzFhOTNlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3ODk5MjcyNDQsImNzcmYiOiJiMWIyYTgwNy1jMjZkLTRhOTQtYjQxNC0zMDE3YWVlYzhlZTIiLCJleHAiOjE3ODk5MzAyNDR9.xgaaHxnDlrLFGKc_ObrIDcbeYlMdw8KQmSj9BlUh5xQ
@librarianToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI5MiwianRpIjoiMGZlMjQ5YmQtMTdlYy00MDI1LTlkNTAtNmU2NjQ3NmEyZWZkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3ODk5MjcyOTIsImNzcmYiOiJjOTE5ZDdhZS05YzJjLTQzODctYWFmMy05M2YzZjkzOWQyMDYiLCJleHAiOjE3ODk5MzAyOTJ9.SQUvrXccC9RK8EEOBV2vNnydq79JxiVHTIKpsmxIYmo
@memberRefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4OTkyNzI0NCwianRpIjoiZDNhMjcyZjYtZDg1Mi00OGQxLTg4NzUtNTdhYzAyNGEyZmQyIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxIiwibmJmIjoxNzg5OTI3MjQ0LCJjc3JmIjoiMGIzMjI0ODUtODAyMS00MTgwLWJiYzctYmFmZmMwZDM2ZWNkIiwiZXhwIjoxNzkyNTE5MjQ0fQ.5XCzZCDksJ3kcKSfN-1qch2y5cOL2qd1C5OYI1l_THk
@baseUrl = http://127.0.0.1:5000

### Get quiz
GET {{baseUrl}}/tests/1
Authorization: Bearer {{memberToken}}

### Submit quiz
POST {{baseUrl}}/tests/1/submit
Authorization: Bearer {{memberToken}}
Content-Type: application/json

{
  "answers": [
    {
      "question_id": 1,
      "answer_id": 1
    }
  ]
}


### SQL: create a minimal quiz
# Run in psql:
# INSERT INTO test_task (title, description, max_score)
# VALUES ('Personality', 'Short test', 10);
#
# INSERT INTO test_questions (question_text, FK_test_teast_id, question_type)
# VALUES ('Do you like reading?', 1, 'single_choice');
#
# INSERT INTO test_answers (FK_tst_que_id, answer_text, is_correct)
# VALUES (1, 'Yes', TRUE), (1, 'No', FALSE);